#!/bin/bash

# Enable the proxy extension in notebook and lab
jupyter serverextension enable --py jupyter_server_proxy
jupyter labextension install @jupyterlab/server-proxy
jupyter lab build

code-server --install-extension ms-python.python

# Install the VS code proxy
pip install -e.

fromdos .vimrc

git clone https://github.com/vim/vim.git
cd vim
./configure --enable-python3interp
make